# service-nameは任意のCloudrunサービス名名
# service-image-nameは任意のコンテナイメージ名

steps:
    # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia.gcr.io/$PROJECT_ID/service-image-name', '.']
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia.gcr.io/$PROJECT_ID/service-image-name']
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    # --allow-unauthenticatedで公開（未認証）アクセスを許可
    # ref: https://cloud.google.com/run/docs/authenticating/public?hl=ja#command-line
    args: [
      'run',
      'deploy',
      'service-name', # サービス名
      '--image',
      'asia.gcr.io/$PROJECT_ID/service-image-name',
      '--region',
      'asia-northeast1',
      '--max-instances',
      '10',
      # --allow-unauthenticatedで公開（未認証）アクセスを許可 (許可範囲変更には初回デプロイ後数分かかる)出来るはずだが以下理由で適用されない場合があるためGUI等で設定
      # ref1: https://stackoverflow.com/a/68085858
      # ref2: https://cloud.google.com/sdk/gcloud/reference/run/deploy
      # '--allow-unauthenticated',
    ]

images:
  - asia.gcr.io/$PROJECT_ID/service-image-name

#options:
#  # https://cloud.google.com/build/pricing?hl=ja
#  machineType: 'E2_HIGHCPU_8'


# deploy, ref: https://issuetracker.google.com/issues/229465311
# gcloud builds submit
# or
# gcloud builds submit --region=asia-northeast1