name: Monorepo test
on: push
env:
  CACHE_VERSION: 1
permissions:
  contents: read # for checkout repository
  actions: read # for fetching base branch bundle stats
  pull-requests: write # for comments
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4

      - name: Enable corepack for pnpm
        run: corepack enable pnpm

      - name: Restore Node cache
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
        with:
          cache: 'pnpm'
          node-version-file: 'package.json'

      - name: Install all packages
        run: pnpm install --frozen-lockfile

      - name: biome check
        run: biome check

      - name: Build check
        run: pnpm build

      - name: Type check
        run: pnpm typecheck
