name: Monorepo test
on: push
env:
  CACHE_VERSION: 1
permissions:
  contents: read # for checkout repository
  actions: read # for fetching base branch bundle stats
  pull-requests: write # for comments
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Enable corepack for pnpm
        run: corepack enable pnpm

      - name: Restore Node cache
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          cache: 'pnpm'
          node-version-file: 'package.json'

      - name: Install all packages
        run: pnpm install --frozen-lockfile

      - name: lint / format check
        run: pnpm check

      - name: Build check
        run: pnpm build

      - name: Type check
        run: pnpm typecheck
