name: Playwright Tests
on: push
jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0

      - name: Enable corepack for pnpm
        run: corepack enable pnpm

      - name: Restore Node cache
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          cache: 'pnpm'
          node-version-file: 'package.json'

      - name: Install all packages
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm test:e2e

      - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
